- hosts: localhost
  gather_facts: false
  vars:
    volume_name: "NewTestVol_123"
    host_name: "10.3.1.9"
    cpg: "v0040_DBaaS_RAC"
    size: 10
    size_unit: 'GiB'


  tasks:
  - name: Create Volume "{{ volume_name }}"
    hpe3par_volume:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_username: "{{ storage_system_username }}"
      storage_system_password: "{{ storage_system_password }}"
      state: present
      volume_name: "{{ volume_name }}"
      cpg: "{{ cpg }}"
      size: "{{ size }}"
      size_unit: "{{ size_unit }}"
    environment:
      no_proxy: "{{ storage_system_ip }}"
      
  - name: Create Hosts
    hpe3par_host_facts:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_username: "{{ storage_system_username }}"
      storage_system_password: "{{ storage_system_password }}"
    register: myhosts
    environment:
      no_proxy: "{{ storage_system_ip }}"


  - set_fact:
      hostname: "{{ item.name }}"
    when: '"50014380331546EC" in item.fcWWNs'
    loop: "{{ myhosts.hosts }}"

  - debug:
      msg: "{{ hostname }}"

