- hosts: localhost
  tasks:
  - name: Gather information about all Network Sets
    oneview_network_set_info:
      hostname: "{{ oneview_hostname }}"
      username: "{{ oneview_username }}"
      password: "{{ oneview_password }}"
      api_version: "{{ api_version }}"
    delegate_to: localhost
    register: result
    
  - debug:
      msg: "{{ result }}"
