- hosts: all
  gather_facts: no
  tasks:
  - name: Create server profile from template
    oneview_server_profile:
      hostname: "{{ oneview_hostname }}"
      username: "{{ oneview_username }}"
      password: "{{ oneview_password }}"
      api_version: "{{ api_version }}"
      state: present
      data:
        name: "{{ profileName }}"
        serverProfileTemplateName: "{{ server_profile_template_name }}"
        serverHardwareName: "{{ hardwareName }}"
      params:
        force: True
    delegate_to: localhost
